<?php
include '../model/query.php';
require_once '../controller/ComplianceMailer.class.php';

if (empty($_SESSION['activeAdmin'])) {
    $utility->notifier('danger', 'Access Denied! Please sign in again.');
    $model->redirect('../login/manager.php');
}

$mailer = new ComplianceMailer($db_conn, $utility);
$returnPage = (string) ($_POST['returnPage'] ?? 'complianceMailer');
if (!in_array($returnPage, ['complianceMailer', 'complianceStatus'], true)) {
    $returnPage = 'complianceMailer';
}
$returnUrl = '../pages/admin/index.php?pageid=' . base64_encode($returnPage);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    $utility->notifier('danger', 'Invalid request method.');
    $model->redirect($returnUrl);
}

$csrfToken = (string) ($_POST['csrfToken'] ?? '');
if (empty($_SESSION['compliance_mail_csrf']) || !hash_equals($_SESSION['compliance_mail_csrf'], $csrfToken)) {
    $utility->notifier('danger', 'Security check failed. Please reload the compliance mailer page and try again.');
    $model->redirect($returnUrl);
}

if (isset($_POST['queueWeeklyComplianceMail'])) {
    try {
        $result = $mailer->queueWeeklyCampaign($_SESSION['activeAdmin']);
        $utility->notifier(
            (int) $result['campaign_id'] > 0 ? 'success' : 'warning',
            ($result['message'] ?? 'Weekly compliance queue prepared.') . ' New: ' . $result['queued'] .
            ', restored from no-email: ' . $result['updated'] .
            ', no email: ' . $result['skipped_no_email'] . '.'
        );
        $user->recordLog($_SESSION['activeAdmin'], 'Compliance Mail Queue', 'Weekly portal compliance queue generated by admin.');
    } catch (Throwable $e) {
        error_log('Compliance queue generation failed: ' . $e->getMessage());
        $utility->notifier('danger', 'Unable to prepare the compliance mail queue. Check the server log.');
    }

    $model->redirect($returnUrl);
}

if (isset($_POST['sendComplianceMailQueue'])) {
    $limit = (int) ($_POST['sendLimit'] ?? 45);

    try {
        $result = $mailer->sendQueued($limit);
        $utility->notifier(
            $result['failed'] > 0 || $result['message'] !== 'Queue processed.' ? 'warning' : 'success',
            $result['message'] . ' Sent: ' . $result['sent'] .
            ', failed: ' . $result['failed'] .
            ', remaining hourly allowance: ' . $result['remaining_hourly_allowance'] . '.'
        );
        $user->recordLog($_SESSION['activeAdmin'], 'Compliance Mail Sender', 'Compliance mail queue manually processed by admin.');
    } catch (Throwable $e) {
        error_log('Compliance queue send failed: ' . $e->getMessage());
        $utility->notifier('danger', 'Unable to send queued compliance mails. Check the server log.');
    }

    $model->redirect($returnUrl);
}

if (isset($_POST['sendComplianceSchoolMail'])) {
    $schoolCode = (string) ($_POST['schCode'] ?? '');

    try {
        $result = $mailer->sendSchoolNotice($schoolCode, $_SESSION['activeAdmin']);
        $utility->notifier(
            $result['failed'] > 0 ? 'warning' : (($result['sent'] > 0 || $result['queued'] > 0) ? 'success' : 'warning'),
            $result['message'] . ' Sent: ' . $result['sent'] . ', queued: ' . $result['queued'] . ', failed: ' . $result['failed'] . '.'
        );
        $user->recordLog($_SESSION['activeAdmin'], 'Compliance School Mail', 'Individual compliance mail requested for school: ' . $schoolCode);
    } catch (Throwable $e) {
        error_log('Individual compliance mail failed: ' . $e->getMessage());
        $utility->notifier('danger', 'Unable to process the individual compliance mail. Check the server log.');
    }

    $model->redirect($returnUrl);
}

if (isset($_POST['addComplianceSchoolEmail'])) {
    $schoolCode = (string) ($_POST['schCode'] ?? '');
    $email = (string) ($_POST['emailAddress'] ?? '');

    try {
        if ($mailer->addSchoolEmail($schoolCode, $email, $_SESSION['activeAdmin'])) {
            $user->recordLog($schoolCode, 'Compliance Email Added', 'Admin added school email address for weekly compliance notices.');
            $utility->notifier('success', 'Email address has been added for ' . $schoolCode . '.');
        } else {
            $utility->notifier('danger', 'Unable to add email address. Confirm the school and email address.');
        }
    } catch (Throwable $e) {
        error_log('Compliance school email add failed: ' . $e->getMessage());
        $utility->notifier('danger', 'Unable to add email address. Check the server log.');
    }

    $model->redirect($returnUrl);
}

$utility->notifier('danger', 'We could not understand your compliance mail request.');
$model->redirect($returnUrl);
